# Logistic Regression on RealPython.com

Understand and use logistic regression model

## Step 1: Import packages, functions, and classes

`matplotlib.pyplot` to visualize data

`numpy` for array related things

`LogisticRegression` to build and use model

`classification_report`

`confusion_matrix` to evaluate model accuracy

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

## Step 2: Get data

Creating arrays for this tutorial

In [2]:
x = np.arange(10).reshape(-1,1)
y = np.array([0,0,0,0,1,1,1,1,1,1])

print('x:\n',x)
print('\ny:\n',y)

x:
 [[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y:
 [0 0 0 0 1 1 1 1 1 1]


## Step 3: Create and train model

In [3]:
model = LogisticRegression(random_state=0)

In [4]:
model.fit(x,y)

LogisticRegression(random_state=0)

In [5]:
model.classes_

array([0, 1])

In [6]:
model.intercept_

array([-4.12617727])

In [7]:
model.coef_

array([[1.18109091]])

## Step 4: Evaluate the model

In [8]:
model.predict_proba(x)

array([[0.98411203, 0.01588797],
       [0.95003074, 0.04996926],
       [0.85370936, 0.14629064],
       [0.64173546, 0.35826454],
       [0.35475873, 0.64524127],
       [0.1443924 , 0.8556076 ],
       [0.04924876, 0.95075124],
       [0.01565079, 0.98434921],
       [0.00485659, 0.99514341],
       [0.00149573, 0.99850427]])

In [9]:
model.predict(x)

array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

In [10]:
model.score(x,y)

1.0

In [11]:
confusion_matrix(y,model.predict(x))

array([[4, 0],
       [0, 6]], dtype=int64)

## Improve model

In [12]:
model = LogisticRegression(C=10., random_state=0).fit(x,y)

In [13]:
model.intercept_

array([-9.36952397])

In [14]:
model.coef_

array([[2.67700725]])

In [15]:
model.predict_proba(x)

array([[9.99914723e-01, 8.52767037e-05],
       [9.98761378e-01, 1.23862163e-03],
       [9.82285691e-01, 1.77143090e-02],
       [7.92243523e-01, 2.07756477e-01],
       [2.07756011e-01, 7.92243989e-01],
       [1.77142597e-02, 9.82285740e-01],
       [1.23861812e-03, 9.98761382e-01],
       [8.52764621e-05, 9.99914724e-01],
       [5.86481322e-06, 9.99994135e-01],
       [4.03317512e-07, 9.99999597e-01]])

In [16]:
model.score(x,y)

1.0

In [17]:
confusion_matrix(y,model.predict(x))

array([[4, 0],
       [0, 6]], dtype=int64)